from __future__ import annotations

import zlib
from dataclasses import dataclass
from functools import cached_property
from itertools import pairwise
from typing import TypeVar

from metile.compiler.schedule_expr import ScheduleProgram, select_schedule_program
from metile.compiler.schedules import SCHEDULES, resolve_schedule, schedule_coordinates
from metile.ir import metal_ir as mir


@dataclass(frozen=True)
class FinitePermutation:
    """An element of the symmetric group over a finite dispatch grid."""

    images: tuple[int, ...]

    def __post_init__(self):
        if sorted(self.images) != list(range(len(self.images))):
            raise ValueError("permutation must contain each index exactly once")

    @classmethod
    def identity(cls, size: int) -> FinitePermutation:
        return cls(tuple(range(size)))

    def compose(self, other: FinitePermutation) -> FinitePermutation:
        if len(self.images) != len(other.images):
            raise ValueError("permutations must act on the same set")
        return FinitePermutation(tuple(self.images[index] for index in other.images))

    def inverse(self) -> FinitePermutation:
        inverse = [0] * len(self.images)
        for source, destination in enumerate(self.images):
            inverse[destination] = source
        return FinitePermutation(tuple(inverse))

    @cached_property
    def cycles(self) -> tuple[tuple[int, ...], ...]:
        remaining = set(range(len(self.images)))
        cycles = []
        while remaining:
            start = min(remaining)
            cycle = []
            current = start
            while current in remaining:
                remaining.remove(current)
                cycle.append(current)
                current = self.images[current]
            cycles.append(tuple(cycle))
        return tuple(cycles)


@dataclass(frozen=True)
class FinitePermutationGroup:
    """A finite permutation group generated by composable actions."""

    degree: int
    generators: tuple[FinitePermutation, ...]

    def __post_init__(self):
        if self.degree <= 0:
            raise ValueError("permutation groups require a positive degree")
        if any(len(generator.images) != self.degree for generator in self.generators):
            raise ValueError("group generators must act on the declared degree")

    @cached_property
    def elements(self) -> tuple[FinitePermutation, ...]:
        identity = FinitePermutation.identity(self.degree)
        discovered = {identity}
        frontier = [identity]
        while frontier:
            element = frontier.pop()
            for generator in self.generators:
                product = element.compose(generator)
                if product not in discovered:
                    discovered.add(product)
                    frontier.append(product)
        return tuple(sorted(discovered, key=lambda element: element.images))

    def orbit(self, index: int) -> tuple[int, ...]:
        if index < 0 or index >= self.degree:
            raise IndexError("group action index is outside the permutation domain")
        return tuple(sorted({element.images[index] for element in self.elements}))

    def stabilizer(self, index: int) -> tuple[FinitePermutation, ...]:
        if index < 0 or index >= self.degree:
            raise IndexError("group action index is outside the permutation domain")
        return tuple(element for element in self.elements if element.images[index] == index)


@dataclass(frozen=True)
class GridSymmetryGroup:
    """Shape-preserving tile-grid symmetries generated as a finite group."""

    grid_m: int
    grid_n: int
    block_m: int = 1
    block_n: int = 1
    axis_interchangeable: bool | None = None

    def __post_init__(self):
        if min(self.grid_m, self.grid_n, self.block_m, self.block_n) <= 0:
            raise ValueError("grid and block dimensions must be positive")

    def _permutation(self, transform) -> FinitePermutation:
        images = []
        for index in range(self.grid_m * self.grid_n):
            m, n = divmod(index, self.grid_n)
            target_m, target_n = transform(m, n)
            images.append(target_m * self.grid_n + target_n)
        return FinitePermutation(tuple(images))

    @cached_property
    def permutation_group(self) -> FinitePermutationGroup:
        generators = [
            self._permutation(lambda m, n: (self.grid_m - 1 - m, n)),
            self._permutation(lambda m, n: (m, self.grid_n - 1 - n)),
        ]
        allow_axis_exchange = self.axis_interchangeable
        if allow_axis_exchange is None:
            allow_axis_exchange = self.block_m == self.block_n
        if allow_axis_exchange and self.grid_m == self.grid_n and self.block_m == self.block_n:
            generators.append(self._permutation(lambda m, n: (n, m)))
        return FinitePermutationGroup(self.grid_m * self.grid_n, tuple(generators))

    @cached_property
    def elements(self) -> tuple[FinitePermutation, ...]:
        return self.permutation_group.elements

    @cached_property
    def name(self) -> str:
        order = len(self.elements)
        if order == 8:
            return "D4"
        if order == 4:
            return "D2"
        if order == 2:
            return "C2"
        if order == 1:
            return "C1"
        return f"G{order}"

    def orbit(self, index: int) -> tuple[int, ...]:
        return self.permutation_group.orbit(index)

    def stabilizer(self, index: int) -> tuple[FinitePermutation, ...]:
        return self.permutation_group.stabilizer(index)

    @cached_property
    def fundamental_domain(self) -> tuple[int, ...]:
        """Return one canonical representative from every group orbit."""
        unassigned = set(range(self.grid_m * self.grid_n))
        representatives = []
        while unassigned:
            seed = min(unassigned)
            orbit = set(self.orbit(seed))
            representatives.append(min(orbit))
            unassigned.difference_update(orbit)
        return tuple(representatives)

    def canonicalize(self, permutation: FinitePermutation) -> tuple[int, ...]:
        """Canonicalize a traversal under shape symmetries of its tile coordinates."""
        images = []
        for symmetry in self.elements:
            images.append(symmetry.compose(permutation).images)
        return min(images)

    def traversal_orbit(self, permutation: FinitePermutation) -> tuple[FinitePermutation, ...]:
        return tuple(
            sorted(
                {symmetry.compose(permutation) for symmetry in self.elements},
                key=lambda element: element.images,
            )
        )


@dataclass(frozen=True)
class ScheduleCost:
    pattern: str
    encoding: str
    description_bits: int
    target_cost: int
    locality_cost: float
    worst_jump: int
    score: float
    permutation: FinitePermutation
    canonical_signature: tuple[int, ...]
    symmetry_group: str
    orbit_size: int
    program: ScheduleProgram


_Candidate = TypeVar("_Candidate")


def compressed_description_bits(source: str) -> int:
    """Return a computable upper bound on source Kolmogorov complexity.

    Kolmogorov complexity itself is uncomputable. Compressed source length is
    a stable minimum-description-length proxy for equivalent representations.
    """
    return len(zlib.compress(source.encode(), level=9)) * 8


def choose_mdl_tie(
    candidates: list[tuple[float, int, _Candidate]],
    relative_tolerance: float = 0.0025,
) -> _Candidate:
    """Choose the shortest representation inside a sub-percent latency tie."""
    if not candidates:
        raise ValueError("at least one measured candidate is required")
    fastest = min(runtime for runtime, _, _ in candidates)
    tied = [
        candidate
        for candidate in candidates
        if candidate[0] <= fastest * (1.0 + relative_tolerance)
    ]
    return min(tied, key=lambda candidate: (candidate[1], candidate[0]))[2]


def analyze_schedule(
    pattern: str,
    grid_m: int,
    grid_n: int,
    block_m: int = 1,
    block_n: int = 1,
    encoding: str = "auto",
    axis_interchangeable: bool | None = None,
) -> ScheduleCost:
    resolved = resolve_schedule(pattern, grid_m, grid_n)
    coordinates = list(schedule_coordinates(grid_m, grid_n, resolved))
    images = tuple(m * grid_n + n for m, n in coordinates)
    permutation = FinitePermutation(images)
    jumps = [
        abs(next_m - current_m) + abs(next_n - current_n)
        for (current_m, current_n), (next_m, next_n) in pairwise(coordinates)
    ]
    locality = sum(jump * jump for jump in jumps) / max(len(jumps), 1)
    program = select_schedule_program(resolved, grid_m, grid_n, encoding)
    description_bits = program.description_bits
    # Locality remains primary. Static instruction cost and description length
    # only distinguish traversals whose cache-distance scores are close.
    score = locality + program.target_cost / 128.0 + description_bits / 8192.0
    symmetry_group = GridSymmetryGroup(
        grid_m,
        grid_n,
        block_m,
        block_n,
        axis_interchangeable,
    )
    return ScheduleCost(
        pattern=resolved,
        encoding=program.encoding,
        description_bits=description_bits,
        target_cost=program.target_cost,
        locality_cost=locality,
        worst_jump=max(jumps, default=0),
        score=score,
        permutation=permutation,
        canonical_signature=symmetry_group.canonicalize(permutation),
        symmetry_group=symmetry_group.name,
        orbit_size=len(symmetry_group.traversal_orbit(permutation)),
        program=program,
    )


def rank_schedules(
    grid_m: int,
    grid_n: int,
    block_m: int = 1,
    block_n: int = 1,
    encoding: str = "auto",
    axis_interchangeable: bool | None = None,
) -> list[ScheduleCost]:
    """Rank inequivalent, valid schedule representations by an MDL proxy."""
    representatives = {}
    for pattern in sorted(SCHEDULES - {"auto"}):
        cost = analyze_schedule(
            pattern,
            grid_m,
            grid_n,
            block_m,
            block_n,
            encoding,
            axis_interchangeable,
        )
        incumbent = representatives.get(cost.canonical_signature)
        if incumbent is None or (cost.score, cost.description_bits, cost.pattern) < (
            incumbent.score,
            incumbent.description_bits,
            incumbent.pattern,
        ):
            representatives[cost.canonical_signature] = cost
    ranked = list(representatives.values())
    return sorted(ranked, key=lambda cost: (cost.score, cost.description_bits, cost.pattern))


def optimize_tile_schedules(function: mir.MFunction) -> mir.MFunction:
    """Resolve schedules to canonical, branch-free expression programs."""
    for op in function.ops:
        if not isinstance(op, mir.MTileSchedule) or op.grid_m is None or op.grid_n is None:
            continue
        if op.pattern == "auto":
            selected = rank_schedules(
                op.grid_m,
                op.grid_n,
                op.block_m,
                op.block_n,
                op.encoding,
                op.axis_interchangeable,
            )[0]
        else:
            selected = analyze_schedule(
                op.pattern,
                op.grid_m,
                op.grid_n,
                op.block_m,
                op.block_n,
                op.encoding,
                op.axis_interchangeable,
            )
        op.pattern = selected.pattern
        op.encoding = selected.encoding
        op.description_bits = selected.description_bits
        op.symmetry_group = selected.symmetry_group
        op.is_static = True
    return function
