"""meTile as an opt-in backend for mlx-lm."""

from metile.integrations.mlx_lm._state import (
    _COMPRESSED_INTERVAL_DIRECTION_BUDGET as _COMPRESSED_INTERVAL_DIRECTION_BUDGET,
)
from metile.integrations.mlx_lm._state import (
    _FUSED_BLOCK_CLASSES as _FUSED_BLOCK_CLASSES,
)
from metile.integrations.mlx_lm._state import (
    _GATED_MLP_CLASSES as _GATED_MLP_CLASSES,
)
from metile.integrations.mlx_lm._state import (
    _compressed_attention_calibration_cache_path as _compressed_attention_calibration_cache_path,
)
from metile.integrations.mlx_lm._state import (
    _compressed_down_calibration_cache_path as _compressed_down_calibration_cache_path,
)
from metile.integrations.mlx_lm._state import (
    _compressed_gate_up_calibration_cache_path as _compressed_gate_up_calibration_cache_path,
)
from metile.integrations.mlx_lm._state import (
    _compressed_vocab_calibration_cache_path as _compressed_vocab_calibration_cache_path,
)
from metile.integrations.mlx_lm._state import (
    _quantized_mlp_executor_cache as _quantized_mlp_executor_cache,
)
from metile.integrations.mlx_lm.apply import (
    apply_metile_to_mlx_lm,
)
from metile.integrations.mlx_lm.autotune import (
    autotune_metile_for_mlx_lm,
)
from metile.integrations.mlx_lm.compressed import (
    MLXCompressedAttention,
    MLXCompressedDown,
    MLXCompressedGateUp,
    MLXCompressedVocab,
    _audit_larger_compressed_regions,
    _augment_compressed_subset,
    _compressed_attention_repack_bytes,
    _compressed_down_subset_candidates,
    _compressed_gate_up_repack_bytes,
    _CompressedCalibrationReference,
    _prepare_compressed_calibration_reference,
    _repack_compressed_attention_group,
    _repack_compressed_gate_up_group,
    _restore_compressed_attention_calibration,
    _restore_compressed_down_calibration,
    _restore_compressed_gate_up_calibration,
    _restore_compressed_vocab_calibration,
    _select_compressed_region,
    _supports_compressed_gate_up_fusion,
    _write_compressed_attention_calibration,
    _write_compressed_down_calibration,
    _write_compressed_gate_up_calibration,
    _write_compressed_gate_up_implementation,
    _write_compressed_vocab_calibration,
    prepare_mlx_lm_compressed_attention,
    prepare_mlx_lm_compressed_down,
    prepare_mlx_lm_compressed_gate_up,
    prepare_mlx_lm_compressed_vocab,
)
from metile.integrations.mlx_lm.core import (
    _attention_module,
    _call_source,
    _decode_shape_key,
    _mlx_lm_model_signature,
    _model_layers,
    _prepare_mlx_lm_prompt,
    _recognised,
    _registry_classes,
    _structurally_matches,
    _supports_metile_decode,
    _supports_metile_rms_norm,
    _tensor_spec,
)
from metile.integrations.mlx_lm.modules import (
    MLXAffinePrefill,
    MLXDenseMLP,
    _execute_dense_mlp,
    _execute_dense_swiglu,
    _execute_quantized_mlp,
    _execute_residual_rms_graph,
    _select_model_affine8_group,
    _supports_dense_residual_mlp,
    _supports_metile_residual_rms_norm,
    _supports_quantized_mlp,
    _supports_quantized_residual_mlp,
    prepare_mlx_lm_affine_prefill,
    prepare_mlx_lm_dense_mlp,
)
from metile.integrations.mlx_lm.patching import (
    MLXPatch,
    _patch_affine_prefill,
    _patch_compressed_attention,
    _patch_compressed_down,
    _patch_compressed_gate_up,
    _patch_compressed_vocab,
    _patch_dense_mlp,
    _patch_graph_fusion,
    _patch_quantized_mlp,
)
from metile.integrations.mlx_lm.plan_model import (
    MLXLMPlan,
    _choose_mlx_lm_plan,
    _compression_ladder,
    _effective_mlx_lm_plan,
    _fidelity_compatible,
    _is_decode_only_compression_plan,
    _logit_fidelity,
    _mlx_lm_plan_candidates,
    _mlx_lm_validation_finalists,
    _mlx_lm_validation_survivors,
    _mlx_lm_warmup_plans,
    _paired_plan_ratios,
    _provisional_mlx_lm_finalists,
    _rank_mlx_lm_plans,
    _read_mlx_lm_plan,
    _write_mlx_lm_plan,
)
from metile.integrations.mlx_lm.tuning import (
    _autotune_compressed_attention_group,
    _autotune_compressed_gate_up_group,
    _cache_aware_dense_fidelity,
    _calibrate_compressed_attention,
    _calibrate_compressed_down,
    _calibrate_compressed_gate_up,
    _calibrate_compressed_vocab,
    _compressed_attention_calibration_key,
    _compressed_attention_group_key,
    _compressed_down_calibration_key,
    _compressed_gate_up_calibration_key,
    _compressed_gate_up_group_key,
    _compressed_gate_up_implementation_key,
    _compressed_region_policy_signature,
    _compressed_vocab_calibration_key,
    _extend_mlx_lm_measurements,
    _measure_mlx_lm_plans,
    _mlx_lm_plan_key,
    _plan_preserves_logits,
    _run_compressed_calibration_candidate,
    _select_compressed_gate_up_implementation,
    _select_dense_mlp_implementation,
    _time_dense_mlp_implementation,
    _time_mlx_lm_plan,
    _validate_mlx_lm_finalists_repeated,
    _validate_mlx_lm_plan,
    _validate_mlx_lm_plan_repeated,
)

__all__ = [
    "MLXAffinePrefill",
    "MLXCompressedAttention",
    "MLXCompressedDown",
    "MLXCompressedGateUp",
    "MLXCompressedVocab",
    "MLXDenseMLP",
    "MLXLMPlan",
    "MLXPatch",
    "_CompressedCalibrationReference",
    "_attention_module",
    "_audit_larger_compressed_regions",
    "_augment_compressed_subset",
    "_autotune_compressed_attention_group",
    "_autotune_compressed_gate_up_group",
    "_cache_aware_dense_fidelity",
    "_calibrate_compressed_attention",
    "_calibrate_compressed_down",
    "_calibrate_compressed_gate_up",
    "_calibrate_compressed_vocab",
    "_call_source",
    "_choose_mlx_lm_plan",
    "_compressed_attention_calibration_key",
    "_compressed_attention_group_key",
    "_compressed_attention_repack_bytes",
    "_compressed_down_calibration_key",
    "_compressed_down_subset_candidates",
    "_compressed_gate_up_calibration_key",
    "_compressed_gate_up_group_key",
    "_compressed_gate_up_implementation_key",
    "_compressed_gate_up_repack_bytes",
    "_compressed_region_policy_signature",
    "_compressed_vocab_calibration_key",
    "_compression_ladder",
    "_decode_shape_key",
    "_effective_mlx_lm_plan",
    "_execute_dense_mlp",
    "_execute_dense_swiglu",
    "_execute_quantized_mlp",
    "_execute_residual_rms_graph",
    "_extend_mlx_lm_measurements",
    "_fidelity_compatible",
    "_is_decode_only_compression_plan",
    "_logit_fidelity",
    "_measure_mlx_lm_plans",
    "_mlx_lm_model_signature",
    "_mlx_lm_plan_candidates",
    "_mlx_lm_plan_key",
    "_mlx_lm_validation_finalists",
    "_mlx_lm_validation_survivors",
    "_mlx_lm_warmup_plans",
    "_model_layers",
    "_paired_plan_ratios",
    "_patch_affine_prefill",
    "_patch_compressed_attention",
    "_patch_compressed_down",
    "_patch_compressed_gate_up",
    "_patch_compressed_vocab",
    "_patch_dense_mlp",
    "_patch_graph_fusion",
    "_patch_quantized_mlp",
    "_plan_preserves_logits",
    "_prepare_compressed_calibration_reference",
    "_prepare_mlx_lm_prompt",
    "_provisional_mlx_lm_finalists",
    "_rank_mlx_lm_plans",
    "_read_mlx_lm_plan",
    "_recognised",
    "_registry_classes",
    "_repack_compressed_attention_group",
    "_repack_compressed_gate_up_group",
    "_restore_compressed_attention_calibration",
    "_restore_compressed_down_calibration",
    "_restore_compressed_gate_up_calibration",
    "_restore_compressed_vocab_calibration",
    "_run_compressed_calibration_candidate",
    "_select_compressed_gate_up_implementation",
    "_select_compressed_region",
    "_select_dense_mlp_implementation",
    "_select_model_affine8_group",
    "_structurally_matches",
    "_supports_compressed_gate_up_fusion",
    "_supports_dense_residual_mlp",
    "_supports_metile_decode",
    "_supports_metile_residual_rms_norm",
    "_supports_metile_rms_norm",
    "_supports_quantized_mlp",
    "_supports_quantized_residual_mlp",
    "_tensor_spec",
    "_time_dense_mlp_implementation",
    "_time_mlx_lm_plan",
    "_validate_mlx_lm_finalists_repeated",
    "_validate_mlx_lm_plan",
    "_validate_mlx_lm_plan_repeated",
    "_write_compressed_attention_calibration",
    "_write_compressed_down_calibration",
    "_write_compressed_gate_up_calibration",
    "_write_compressed_gate_up_implementation",
    "_write_compressed_vocab_calibration",
    "_write_mlx_lm_plan",
    "apply_metile_to_mlx_lm",
    "autotune_metile_for_mlx_lm",
    "prepare_mlx_lm_affine_prefill",
    "prepare_mlx_lm_compressed_attention",
    "prepare_mlx_lm_compressed_down",
    "prepare_mlx_lm_compressed_gate_up",
    "prepare_mlx_lm_compressed_vocab",
    "prepare_mlx_lm_dense_mlp",
]
